### ISSUE TITLE
Submit job error

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/cloud#166]
```bash
paddlecloud submit -cpu 1 -entry "ls /pfs/dc_mulan/home/yanxu05@baidu.com/" -gpu 0 -jobname test -parallelism 200 -passes 1 -pscpu 1 -pservers 1 -psmemory 1Gi  -memory 1Gi /pfs/dc_mulan/home/yanxu05/idl/idl-dl/pcloud/yanxu
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1270eac]

goroutine 1 [running]:
github.com/PaddlePaddle/cloud/go/paddlecloud.(*Submitter).Submit.func1(0x7fff5fbffa91, 0x32, 0x0, 0x0, 0x143a480, 0xc42001b3e0, 0x20, 0x12c2b00)
	/Users/yanxu05/go/src/github.com/PaddlePaddle/cloud/go/paddlecloud/submit.go:106 +0x4c
path/filepath.Walk(0x7fff5fbffa91, 0x32, 0xc4200d2d20, 0x6, 0x60)
	/usr/local/Cellar/go/1.8/libexec/src/path/filepath/path.go:396 +0x8f
github.com/PaddlePaddle/cloud/go/paddlecloud.(*Submitter).Submit(0xc42004de18, 0x7fff5fbffa91, 0x32, 0x7fff5fbffa42, 0x4, 0xc42004de40, 0x12705da)
	/Users/yanxu05/go/src/github.com/PaddlePaddle/cloud/go/paddlecloud/submit.go:113 +0xa3
github.com/PaddlePaddle/cloud/go/paddlecloud.(*SubmitCmd).Execute(0xc420086180, 0x143e000, 0xc420014260, 0xc420071140, 0x0, 0x0, 0x0, 0x1306a55)
	/Users/yanxu05/go/src/github.com/PaddlePaddle/cloud/go/paddlecloud/submit.go:82 +0x103
github.com/google/subcommands.(*Commander).Execute(0xc4200580e0, 0x143e000, 0xc420014260, 0x0, 0x0, 0x0, 0x0)
	/Users/yanxu05/go/src/github.com/google/subcommands/subcommands.go:141 +0x386
github.com/google/subcommands.Execute(0x143e000, 0xc420014260, 0x0, 0x0, 0x0, 0xc4200001a0)
	/Users/yanxu05/go/src/github.com/google/subcommands/subcommands.go:371 +0x5f
main.main()
	/Users/yanxu05/go/src/github.com/PaddlePaddle/cloud/go/cmd/paddlecloud/paddlecloud.go:30 +0x376
```

**Comment by typhoonzero** [comment]
May due to package path is not a local dir
