### ISSUE TITLE
Running fault tolernet jobs encounter panic: context deadline exceeded

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/cloud#464]
```
label selector: paddle-job-pserver=mnist5, desired: 10
label selector: paddle-job-master=mnist5, desired: 1
Starting training job:  /pfs/mulan/home/wuyi05@baidu.com/jobs/mnist5, num_gradient_servers: 5, version:
I1102 03:27:33.970584    30 Util.cpp:166] commandline:  --num_gradient_servers=5 --ports_num_for_sparse=1 --use_gpu=0 --trainer_count=1 --num_passes=1 --ports_num=1 --port=7164
[INFO 2017-11-02 03:27:35,513 layers.py:2556] output for __conv_pool_0___conv: c = 20, h = 24, w = 24, size = 11520
[INFO 2017-11-02 03:27:35,514 layers.py:2684] output for __conv_pool_0___pool: c = 20, h = 12, w = 12, size = 2880
[INFO 2017-11-02 03:27:35,514 layers.py:2556] output for __conv_pool_1___conv: c = 50, h = 8, w = 8, size = 3200
[INFO 2017-11-02 03:27:35,515 layers.py:2684] output for __conv_pool_1___pool: c = 50, h = 4, w = 4, size = 800
I1102 03:27:35.520740    30 GradientMachine.cpp:94] Initing parameters..
I1102 03:27:35.522634    30 GradientMachine.cpp:101] Init parameters done.
panic: context deadline exceeded

goroutine 17 [running, locked to thread]:
main.paddle_new_etcd_master_client(0x7fc7bbffb4d4, 0x5, 0x40, 0x1c400000008)
	/paddle/build/go/src/github.com/PaddlePaddle/Paddle/go/master/c/client.go:85 +0x132
main._cgoexpwrap_3d60921c95c9_paddle_new_etcd_master_client(0x7fc7bbffb4d4, 0x5, 0x40, 0xd8bb14b74dceb600)
	command-line-arguments/_obj/_cgo_gotypes.go:100 +0x41
Aborted
job returned 134...setting pod return message...
===============================
termination log wroted...
```

**Comment by helinwang** [comment]
Maybe change here: https://github.com/PaddlePaddle/Paddle/blob/8c9119afcd63eedefa93d08339c773a128a285a5/python/paddle/v2/reader/creator.py#L91
